#!/usr/bin/env python3
"""Verify the public docs corpus against the code it claims to describe.

Mechanical checks only — no model in the loop. What it enforces:

1. **Allowlist exactness, both directions**, against `git ls-files docs/`: every tracked
   file has a manifest entry, and every manifest entry names a tracked file. One direction
   is not enough — an entry naming an existing-but-untracked file passes locally while the
   pushed commit does not contain it, so the corpus verified is not the corpus published.
2. **Admitted extensions only** (`.md`, `.txt`, `.yaml`), checked across everything tracked
   under `docs/` rather than only manifested entries. A binary is skipped by the deny sweep
   and cannot be read in review, so it has no place in a corpus whose claim is auditability.
3. **Manifest schema**: required fields, correct types, table-safe strings, no duplicates,
   no traversal, no symlinks, no whitespace in paths. Malformed YAML is a finding, not a
   traceback.
4. **Anchors resolve and stay inside the published commit**: `file:line` is rejected
   outright, and so are absolute paths, traversal, and paths git does not track.
5. **Growth budget**: documents ≤ 25 KB so one fits in context beside the code it
   describes; generated indexes ≤ 40 KB. Nothing shards on its own — exceeding it fails.
6. **Structure**: every document carries exactly one ordered SOURCEMAP marker pair, or its
   generated map silently does not exist.
7. **Invariants**: defined once, every reference resolves, and `defines_invariants` matches
   what is actually in the file — both directions.
8. **The corpus skeleton exists**: a manifest holding only its own meta entry would
   otherwise pass every check above while the navigation surfaces had been deleted.

Usage:
    python -m scripts.verify_docs [repo_root] [--report] [--write-nav] [--check-nav]
    printf '%s\\n' <changed-paths> | python -m scripts.verify_docs . --impact \\
        [--base-manifest <path>]
"""
from __future__ import annotations

import ast
import re
import subprocess
import sys
from pathlib import Path

import yaml

LINE_ANCHOR = re.compile(r"^[^:]+:\d+$")
INV_DEFINITION = re.compile(r"\*\*(INV-[A-Z]+-\d+)\*\*\s*:")
INV_REFERENCE = re.compile(r"\b(INV-[A-Z]+-\d+)\b")

CEILING_BYTES = 25_000
WARN_BYTES = 20_000
INDEX_CEILING_BYTES = 40_000

DOCUMENT_KINDS = {"document"}
INDEX_KINDS = {"index", "generated", "meta"}
ALL_KINDS = DOCUMENT_KINDS | INDEX_KINDS
ALLOWED_SUFFIXES = {".md", ".txt", ".yaml"}
ALLOWED_TOP_DIRS = {"architecture", "doctrine", "contributing", "reference"}
TABLE_SAFE_FIELDS = ("summary", "when_changing")
LIST_FIELDS = ("covers", "tests", "related", "defines_invariants")

# An invariant bound to this literal has NO pinning test yet. The sentinel exists so the
# backlog is mechanical: the verifier is red until every sentinel is replaced by a real
# test that has been demonstrated to fail when the invariant is false.
PINNING_SENTINEL = "tests/PINNING-TEST-MISSING"

REQUIRED_SKELETON = {
    "README.md",
    "llms.txt",
    "manifest.yaml",
    "doctrine/invariants.md",
    "doctrine/invariants-n-z.md",
    "doctrine/publishing.md",
    "contributing/doc-contract.md",
}

ROUTING_BEGIN, ROUTING_END = "<!-- BEGIN ROUTING -->", "<!-- END ROUTING -->"
SOURCEMAP_BEGIN, SOURCEMAP_END = "<!-- BEGIN SOURCEMAP -->", "<!-- END SOURCEMAP -->"
GENERATED_NOTE = "<!-- generated by scripts/verify_docs.py --write-nav; do not hand-edit -->"
CODE_WINS = (
    "> Code is the source of truth. This file is a map; when it and the code disagree, "
    "the code wins."
)

SECTIONS = (
    ("Architecture", "architecture/"),
    ("Reference", "reference/"),
    ("Doctrine", "doctrine/"),
    ("Contributing", "contributing/"),
)


# --- anchors -------------------------------------------------------------------------

def parse_anchor(anchor: str) -> tuple[str, str | None]:
    """Split `path::Dotted.Symbol` into its parts. A bare path yields no symbol."""
    if "::" in anchor:
        path, symbol = anchor.split("::", 1)
        return path, symbol
    return anchor, None


def symbol_exists(path: Path, dotted: str) -> bool:
    """Resolve a dotted symbol (`Class.method`, `func`) in a Python file."""
    try:
        tree: ast.AST = ast.parse(path.read_text())
    except (OSError, SyntaxError, ValueError):
        return False
    node = tree
    for part in dotted.split("."):
        for child in ast.iter_child_nodes(node):
            if getattr(child, "name", None) == part:
                node = child
                break
        else:
            return False
    return True


def yaml_key_exists(path: Path, dotted: str) -> bool:
    """Resolve a dotted key path in a YAML file."""
    try:
        data = yaml.safe_load(path.read_text())
    except (OSError, yaml.YAMLError):
        return False
    for part in dotted.split("."):
        if not isinstance(data, dict) or part not in data:
            return False
        data = data[part]
    return True


# --- git ground truth ----------------------------------------------------------------

def _git(repo_root: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(repo_root), *args],
        capture_output=True, text=True, check=True,
    ).stdout


def tracked_files(repo_root: Path) -> set[str]:
    """Every path git tracks, repo-relative.

    An anchor must name one of these: without the check it could point at ignored or local
    content — `.claude/…`, a venv — and pass while being absent from the public commit,
    which is exactly what the publication rule forbids. A dirty-tree check does not notice
    ignored files.
    """
    return {line for line in _git(repo_root, "ls-files").splitlines() if line.strip()}


def tracked_docs(repo_root: Path) -> set[str]:
    """Every file git tracks under docs/, relative to docs/.

    A glob over `*.md` would miss `docs/dump.json`, an image, or an extensionless file —
    all of which would be published without ever appearing in the manifest.
    """
    prefix = "docs/"
    return {
        line[len(prefix):]
        for line in _git(repo_root, "ls-files", prefix).splitlines()
        if line.strip()
    }


# --- manifest ------------------------------------------------------------------------

class _DuplicateKeyLoader(yaml.SafeLoader):
    """PyYAML silently keeps the LAST of a duplicate key, so a manifest entry can carry two
    `covers` blocks and quietly publish only one. Reject them instead."""


def _no_duplicate_keys(loader, node, deep=False):
    seen, dupes = set(), []
    for key_node, _ in node.value:
        key = loader.construct_object(key_node, deep=True)
        if key in seen:
            dupes.append(key)
        seen.add(key)
    if dupes:
        raise yaml.YAMLError(f"duplicate key(s) in a manifest entry: {sorted(dupes)}")
    return yaml.SafeLoader.construct_mapping(loader, node, deep)


_DuplicateKeyLoader.construct_mapping = _no_duplicate_keys


def _manifest_files(docs_dir: Path) -> list[Path]:
    """The root manifest plus every shard, in a deterministic order (#367).

    `manifest.yaml` is required and stays the entry point; when it reaches the
    index ceiling, entries move to `manifest.d/<name>.yaml` shards. Each shard
    is a plain top-level list, exactly like the root, and each shard FILE must
    itself carry a manifest entry (publication is allowlist-only)."""
    return [docs_dir / "manifest.yaml"] + sorted((docs_dir / "manifest.d").glob("*.yaml"))


def _load_entries(docs_dir: Path) -> tuple[list[dict], list[str]]:
    """Parse the manifest (root + `manifest.d/` shards), normalising anything a
    later caller would trip over.

    Normalisation happens HERE rather than per-entry because `verify()` builds sets from
    these values before per-entry validation runs, and `kind: []` is unhashable.
    """
    raw: list = []
    problems: list[str] = []
    for source in _manifest_files(docs_dir):
        label = f"docs/{source.relative_to(docs_dir)}"
        try:
            part = yaml.load(source.read_text(), _DuplicateKeyLoader)
        except yaml.YAMLError as exc:
            return [], [f"{label} is not valid YAML: {exc}"]
        except OSError as exc:
            return [], [f"{label} is unreadable: {exc}"]
        if not isinstance(part, list):
            return [], [f"{label} must be a list of entries"]
        raw.extend(part)

    entries: list[dict] = []
    for index, entry in enumerate(raw):
        if not isinstance(entry, dict) or not isinstance(entry.get("doc"), str):
            problems.append(f"manifest entry {index} is not a mapping with a string `doc` key")
            continue
        if "kind" in entry and not isinstance(entry["kind"], str):
            problems.append(f"{entry['doc']}: `kind` must be a string")
            entry["kind"] = "document"
        for field in LIST_FIELDS:
            value = entry.get(field)
            if value is not None and (
                not isinstance(value, list)
                or not all(isinstance(item, str) for item in value)
            ):
                problems.append(f"{entry['doc']}: `{field}` must be a list of strings")
                entry[field] = []
        bindings = entry.get("invariant_tests")
        if bindings is not None and not (
            isinstance(bindings, dict)
            and all(
                isinstance(inv, str)
                and isinstance(tests, list)
                and all(isinstance(t, str) for t in tests)
                for inv, tests in bindings.items()
            )
        ):
            problems.append(
                f"{entry['doc']}: `invariant_tests` must be a mapping of invariant id to "
                f"a list of test references"
            )
            entry["invariant_tests"] = {}
        entries.append(entry)
    return entries, problems


def _check_entry_shape(entry: dict, seen: set[str]) -> list[str]:
    doc = entry["doc"]
    problems: list[str] = []

    if doc in seen:
        problems.append(f"manifest: {doc!r} is listed twice")
    seen.add(doc)

    if doc != doc.strip() or any(ch.isspace() for ch in doc):
        problems.append(
            f"{doc!r}: manifest paths must not contain whitespace — they pass through "
            f"shell pipelines in CI"
        )

    kind = entry.get("kind", "document")
    if kind not in ALL_KINDS:
        problems.append(f"{doc}: unknown kind {kind!r}")
        entry["kind"] = "document"
        kind = "document"

    required = ("summary", "when_changing") if kind in DOCUMENT_KINDS else ("summary",)
    for field in required:
        value = entry.get(field)
        if value is None or (isinstance(value, str) and not value.strip()):
            problems.append(f"{doc}: `{field}` is required")
    for field in TABLE_SAFE_FIELDS:
        value = entry.get(field)
        if value is None:
            continue
        if not isinstance(value, str):
            problems.append(f"{doc}: `{field}` must be a string")
        elif "|" in value or "\n" in value:
            problems.append(
                f"{doc}: `{field}` must be single-line and free of `|` — it is rendered "
                f"into a Markdown table"
            )
    return problems


def _contained(root: Path, rel: str) -> Path | None:
    """Resolve `rel` under `root`, or None if it escapes. Absolute paths always escape."""
    candidate = Path(rel)
    if candidate.is_absolute() or ".." in candidate.parts:
        return None
    target = root / candidate
    try:
        target.resolve(strict=False).relative_to(root.resolve(strict=False))
    except ValueError:
        return None
    return target


def _resolve_doc(docs_dir: Path, doc: str) -> tuple[Path | None, list[str]]:
    """Reject anything that is not a plain relative path to a permitted regular file."""
    target = docs_dir / doc
    # Symlinks first: a symlink to /etc/passwd "exists" and resolves outside docs/, and the
    # clearer error is that the corpus holds regular files only.
    if target.is_symlink():
        return None, [f"{doc}: is a symlink; the corpus contains regular files only"]
    if _contained(docs_dir, doc) is None:
        return None, [f"{doc}: manifest paths must stay inside docs/ — this points outside"]
    if target.suffix not in ALLOWED_SUFFIXES:
        return None, [
            f"{doc}: extension {target.suffix or '(none)'} is not admitted — the corpus "
            f"holds {', '.join(sorted(ALLOWED_SUFFIXES))} only, because nothing else can "
            f"be swept or read in review"
        ]
    if not target.exists():
        return None, [f"manifest names {doc!r} but the file does not exist"]
    if not target.is_file():
        return None, [f"{doc}: is not a regular file"]
    return target, []


def _check_anchor(repo_root: Path, anchor: str, doc: str, tracked: set[str]) -> list[str]:
    if LINE_ANCHOR.match(anchor):
        return [f"{doc}: line-number anchor {anchor!r} — use path::Symbol instead"]
    rel, symbol = parse_anchor(anchor)
    target = _contained(repo_root, rel)
    if target is None:
        return [
            f"{doc}: anchor {anchor!r} points outside the repository — a doc may only "
            f"anchor to what the public commit contains"
        ]
    if rel not in tracked:
        return [
            f"{doc}: anchor {anchor!r} is not tracked by git — a doc may only anchor to "
            f"what the public commit contains, not to ignored or local files"
        ]
    # A TRACKED symlink whose destination is untracked would otherwise pass: the lexical
    # path is in the tree, and symbol resolution then reads the destination's contents.
    # Same for a gitlink, whose files are not in this commit at all.
    if target.is_symlink():
        return [
            f"{doc}: anchor {anchor!r} is a symlink — it resolves to content that may not "
            f"be in the public commit; anchor the real path"
        ]
    if target.exists() and not target.is_file():
        return [f"{doc}: anchor {anchor!r} is not a regular file"]
    if not target.exists():
        return [f"{doc}: anchor {anchor!r} names a file that does not exist"]
    if symbol is None:
        return []
    if target.suffix == ".py":
        ok = symbol_exists(target, symbol)
    elif target.suffix in (".yaml", ".yml"):
        ok = yaml_key_exists(target, symbol)
    else:
        return [f"{doc}: anchor {anchor!r} — symbols resolve only in .py/.yaml"]
    return [] if ok else [f"{doc}: anchor {anchor!r} does not resolve"]


# Tokens that look like code but are prose or well-known non-source names. Anything added
# here is a deliberate exemption and should be rare.
PROSE_TOKENS = {
    "CLAUDE.md", "AGENTS.md", "DOCS.md", "README.md", "SKILL.md", "config.yaml",
    "manifest.yaml", "llms.txt", "Dockerfile", "dependencies.d", "s6-rc.d", "type",
}
# `foo.py`, `Thing.method`, `func()` — the shapes that assert a code identifier exists.
PROSE_CODE = re.compile(
    r"`("
    r"[a-z_][a-z0-9_]*\.py"                     # a module
    r"|[A-Z][A-Za-z0-9_]*\.[a-z_][a-z0-9_]*"    # Class.method
    r"|_?[a-z][a-z0-9_]{3,}\(\)"               # func()
    r")`"
)


def _code_identifiers(text: str) -> set[str]:
    return {m.group(1) for m in PROSE_CODE.finditer(text)} - PROSE_TOKENS


def _defined_symbols(repo_root: Path, tracked: set[str]) -> tuple[set[str], set[str]]:
    """Every module basename and every def/class name git tracks. Built once per run."""
    modules: set[str] = set()
    names: set[str] = set()
    for rel in tracked:
        if not rel.endswith(".py"):
            continue
        modules.add(Path(rel).name)
        try:
            tree = ast.parse((repo_root / rel).read_text())
        except (OSError, SyntaxError, ValueError):
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                names.add(node.name)
        # Every class anywhere, not only top-level ones: a method of a nested class is still
        # a method, and treating it as unqualified would flag honest prose.
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                for sub in node.body:
                    if isinstance(sub, (ast.FunctionDef, ast.AsyncFunctionDef)):
                        names.add(f"{node.name}.{sub.name}")
                    # Class-level attributes are as citable as methods, and most of this
                    # codebase's data types are dataclasses whose fields are bare
                    # annotations. Collecting only callables flagged `GrantKey.artifact_id`
                    # and `VoiceJob.delivery_modality`, both of which plainly exist.
                    elif isinstance(sub, ast.AnnAssign) and isinstance(sub.target, ast.Name):
                        names.add(f"{node.name}.{sub.target.id}")
                    elif isinstance(sub, ast.Assign):
                        for target in sub.targets:
                            if isinstance(target, ast.Name):
                                names.add(f"{node.name}.{target.id}")
    return modules, names


def _check_prose_code(text: str, doc: str, modules: set[str], names: set[str]) -> list[str]:
    """A document must not name code that does not exist.

    Review found this exact failure: prose citing a method that had been deleted, and a
    private spec asserting ten modules that are gone. Anchors were already checked; the
    PROSE was not, and prose is what a reader acts on.
    """
    problems = []
    for token in sorted(_code_identifiers(text)):
        if token.endswith(".py"):
            ok = token in modules
        elif token.endswith("()"):
            bare = token[:-2]
            ok = bare in names or any(n.endswith(f".{bare}") for n in names)
        else:
            # `Class.method`. An exact hit is fine, and so is a method the class inherits —
            # the qualified set only records where a method is *defined*. What is refused is
            # a bare function or a closure dressed up as a method: `Agent._attempt_bypass_turn`
            # reads as an attribute of Agent, and a reader who greps the class will not find
            # it. That sentence was written, published and wrong; this is the check for it.
            bare = token.split(".")[-1]
            methods = {n.split(".")[-1] for n in names if "." in n}
            if token in names or bare in methods:
                ok = True
            elif bare in names:
                problems.append(
                    f"{doc}: names `{token}` in prose, but `{bare}` is not a method of any "
                    f"class — it is a plain function or a nested closure. Name it without "
                    f"the class prefix, or say where it actually lives."
                )
                continue
            else:
                ok = False
        if not ok:
            problems.append(
                f"{doc}: names `{token}` in prose, which does not exist in the tracked code"
            )
    return problems


def _check_invariant_tests(entry: dict, repo_root: Path, tracked: set[str]) -> list[str]:
    """Every invariant must name a test that fails if the invariant is false.

    Without this an invariant is an assertion, not a contract: the corpus stays green
    while the property it states quietly stops being true. The binding is checked both
    ways — a declared invariant with no test is refused, and so is a binding for an
    invariant the entry no longer declares, which would keep a dead test looking
    load-bearing.
    """
    doc = entry["doc"]
    declared = entry.get("defines_invariants") or []
    bindings = entry.get("invariant_tests") or {}
    problems: list[str] = []
    for inv in declared:
        refs = bindings.get(inv) or []
        if not refs:
            problems.append(
                f"{doc}: {inv} has no pinning test — bind one in `invariant_tests`, or "
                f"the sentinel {PINNING_SENTINEL} to record the debt visibly"
            )
            continue
        for ref in refs:
            if ref == PINNING_SENTINEL:
                problems.append(
                    f"{doc}: {inv} is bound to {PINNING_SENTINEL} — the invariant has no "
                    f"pinning test yet; write one and demonstrate its red case"
                )
                continue
            rel, node = parse_anchor(ref)
            if rel not in tracked:
                problems.append(
                    f"{doc}: {inv} names {ref!r} but git does not track {rel!r} — a "
                    f"pinning test must be in the published commit"
                )
                continue
            if node is None:
                continue
            if "::" in node:
                # A class-qualified pytest node id (`Class::method`) — a
                # RUNNABLE anchor (`pytest {rel}::{node}` works verbatim
                # for a test nested in a class). Python source never
                # contains a literal "::" between a class and its
                # method, so the plain substring search below can never
                # match this shape; verify it structurally instead via
                # the same AST symbol resolution `covers:` entries use.
                if not symbol_exists(repo_root / rel, node.replace("::", ".")):
                    problems.append(
                        f"{doc}: {inv} names {ref!r} but {node!r} does not "
                        f"resolve in {rel}"
                    )
                continue
            # A plain string search, not pytest collection: cheap, dependency-free, and
            # enough to catch a renamed or deleted test function.
            try:
                text = (repo_root / rel).read_text(errors="replace")
            except OSError:
                text = ""
            if node not in text:
                problems.append(
                    f"{doc}: {inv} names {ref!r} but {node!r} does not appear in {rel}"
                )
    for inv in sorted(set(bindings) - set(declared)):
        problems.append(
            f"{doc}: invariant_tests binds {inv}, which the entry does not declare in "
            f"defines_invariants"
        )
    return problems


def _check_sourcemap(target: Path, doc: str) -> list[str]:
    """A document without exactly one ordered marker pair gets no generated map at all."""
    text = target.read_text(errors="replace")
    begins, ends = text.count(SOURCEMAP_BEGIN), text.count(SOURCEMAP_END)
    if begins != 1 or ends != 1:
        return [
            f"{doc}: must contain exactly one SOURCEMAP marker pair (found {begins} begin, "
            f"{ends} end) — otherwise its Source & test map is never generated"
        ]
    if text.index(SOURCEMAP_BEGIN) > text.index(SOURCEMAP_END):
        return [f"{doc}: SOURCEMAP markers are reversed"]
    return []


def _budget_for(kind: str) -> int:
    return CEILING_BYTES if kind in DOCUMENT_KINDS else INDEX_CEILING_BYTES


def _check_invariants(docs_dir: Path, entries: list[dict]) -> list[str]:
    defined: dict[str, list[str]] = {}
    statements: dict[str, str] = {}
    referenced: dict[str, str] = {}
    per_doc: dict[str, set[str]] = {}

    for entry in entries:
        doc = entry["doc"]
        target = docs_dir / doc
        if target.is_symlink() or not target.is_file():
            continue
        text = target.read_text(errors="replace")
        per_doc[doc] = set()
        for line in text.splitlines():
            match = INV_DEFINITION.search(line)
            if match:
                inv = match.group(1)
                defined.setdefault(inv, []).append(doc)
                statements[inv] = line.split(":", 1)[1].strip()
                per_doc[doc].add(inv)
        for inv in INV_REFERENCE.findall(text):
            referenced.setdefault(inv, doc)

    problems: list[str] = []
    for inv, homes in sorted(defined.items()):
        if len(homes) > 1:
            problems.append(
                f"{inv} is defined {len(homes)} times ({', '.join(sorted(homes))}) — an "
                f"invariant has exactly one defining file"
            )
        statement = statements.get(inv, "")
        if not statement:
            problems.append(f"{inv}: has no statement on its definition line")
        if "|" in statement:
            problems.append(f"{inv}: the statement must be free of `|` — it renders into a table")
        # A wrapped statement renders TRUNCATED into the generated table, because only the
        # definition line is captured. Terminal punctuation is a HEURISTIC for that, not a
        # proof: a complete first sentence followed by an essential qualification on the next
        # line still passes here, and only a reviewer catches it.
        if statement and statement[-1] not in ".!?":
            problems.append(
                f"{inv}: the statement must be complete on ONE line (it ends with "
                f"{statement[-12:]!r}). A wrapped statement is truncated in the generated "
                f"invariant index."
            )
    for inv, where in sorted(referenced.items()):
        if inv not in defined:
            problems.append(f"{where}: {inv} is referenced but never defined")

    for entry in entries:
        doc = entry["doc"]
        declared = set(entry.get("defines_invariants") or [])
        actual = per_doc.get(doc, set())
        for inv in sorted(declared - actual):
            problems.append(f"{doc}: manifest declares {inv} but the file does not define it")
        for inv in sorted(actual - declared):
            problems.append(f"{doc}: defines {inv} but the manifest does not declare it")
    return problems


# --- the verifier --------------------------------------------------------------------

def verify(repo_root: Path) -> list[str]:
    """Return every problem found in the corpus. Empty list means clean."""
    docs_dir = repo_root / "docs"
    if not (docs_dir / "manifest.yaml").exists():
        return ["docs/manifest.yaml is missing — the corpus is allowlist-only"]

    entries, problems = _load_entries(docs_dir)
    if problems and not entries:
        return problems

    manifested = {entry["doc"] for entry in entries}
    modules, names = _defined_symbols(repo_root, tracked_files(repo_root))
    # `related` must name a real DOCUMENT: the manifest, the README and the generated
    # indexes are all manifested but are not things to go read next.
    related_targets = {
        entry["doc"] for entry in entries
        if entry.get("kind", "document") in DOCUMENT_KINDS
    }
    tracked = tracked_files(repo_root)

    seen: set[str] = set()
    for entry in entries:
        doc = entry["doc"]
        problems.extend(_check_entry_shape(entry, seen))
        kind = entry.get("kind", "document")

        parts = Path(doc).parts
        top = parts[0] if len(parts) > 1 else ""
        if top == "manifest.d":
            # #367: manifest shards only. A document hidden here would escape
            # the routing table and the generated index.
            if kind in DOCUMENT_KINDS:
                problems.append(
                    f"{doc}: manifest.d/ holds manifest shards only — a document "
                    f"must live under one of {', '.join(sorted(ALLOWED_TOP_DIRS))}/"
                )
        elif top and top not in ALLOWED_TOP_DIRS:
            problems.append(
                f"{doc}: {top}/ is not an admitted corpus directory "
                f"({', '.join(sorted(ALLOWED_TOP_DIRS))})"
            )
        # A root-level `document` verifies cleanly but render_llms only emits the three
        # configured prefixes, so it would be absent from the flat index it claims to be in.
        if not top and kind in DOCUMENT_KINDS:
            problems.append(
                f"{doc}: a document must live under one of "
                f"{', '.join(sorted(ALLOWED_TOP_DIRS))}/ — a root-level document is omitted "
                f"from the generated index"
            )

        target, path_problems = _resolve_doc(docs_dir, doc)
        problems.extend(path_problems)
        if target is None:
            continue

        size = target.stat().st_size
        budget = _budget_for(kind)
        if size > budget:
            label = "25 KB ceiling" if budget == CEILING_BYTES else "40 KB index ceiling"
            problems.append(
                f"{doc} is {size / 1000:.1f} KB — exceeds the {label}. Split it and "
                f"manifest both halves; the ceiling is not raised, and nothing shards "
                f"on its own."
            )

        if kind in DOCUMENT_KINDS:
            problems.extend(_check_sourcemap(target, doc))
            problems.extend(
                _check_prose_code(target.read_text(errors="replace"), doc, modules, names)
            )
            # An invariant is a claim about what the code maintains, so the document must
            # name where it is maintained. Review found invariants asserted with the anchor
            # pointing at a nearby representative symbol instead of the enforcement point;
            # this cannot prove the anchor is the RIGHT one, but an invariant with nothing
            # to check it against is an assertion, not a contract.
            if (entry.get("defines_invariants") or []) and not (entry.get("covers") or []):
                problems.append(
                    f"{doc}: declares invariants but anchors no source — name the code that "
                    f"maintains them in `covers`"
                )
            problems.extend(_check_invariant_tests(entry, repo_root, tracked))

        for anchor in list(entry.get("covers") or []) + list(entry.get("tests") or []):
            problems.extend(_check_anchor(repo_root, anchor, doc, tracked))
        for rel in entry.get("related") or []:
            if _contained(docs_dir, rel) is None or (docs_dir / rel).is_symlink():
                problems.append(f"{doc}: related {rel!r} must be a plain path inside docs/")
            elif rel not in related_targets:
                problems.append(
                    f"{doc}: related {rel!r} is not a manifested document (indexes, the "
                    f"README and the manifest are not related targets)"
                )

    tracked_under_docs = tracked_docs(repo_root)
    # Extensions are checked across EVERYTHING tracked, not only manifested entries: an
    # unmanifested `.png` would otherwise report only "not in the manifest", and the rule
    # would never fire on the files most likely to violate it.
    for rel in sorted(tracked_under_docs):
        if Path(rel).suffix not in ALLOWED_SUFFIXES:
            problems.append(
                f"docs/{rel}: extension {Path(rel).suffix or '(none)'} is not admitted"
            )
    for extra in sorted(tracked_under_docs - manifested):
        problems.append(
            f"docs/{extra} is tracked but not in the manifest — publication is allowlist-only"
        )
    for phantom in sorted(manifested - tracked_under_docs):
        problems.append(
            f"{phantom} is in the manifest but git does not track it — the pushed commit "
            f"will not contain it, so the corpus verified is not the corpus published"
        )

    for missing in sorted(REQUIRED_SKELETON - manifested):
        problems.append(f"{missing} is required by the corpus contract but is not manifested")
    if not any(entry.get("kind", "document") in DOCUMENT_KINDS for entry in entries):
        problems.append("the corpus contains no documents — only indexes and metadata")

    problems.extend(_check_invariants(docs_dir, entries))
    return problems


def warnings(repo_root: Path) -> list[str]:
    """Non-fatal growth pressure, printed by CI so it is visible before it fails."""
    docs_dir = repo_root / "docs"
    if not (docs_dir / "manifest.yaml").exists():
        return []
    entries, _ = _load_entries(docs_dir)
    out = []
    for entry in entries:
        if entry.get("kind", "document") not in DOCUMENT_KINDS:
            continue
        target = docs_dir / entry["doc"]
        if target.is_symlink() or not target.is_file():
            continue
        size = target.stat().st_size
        if WARN_BYTES <= size <= CEILING_BYTES:
            out.append(
                f"{entry['doc']} is {size / 1000:.1f} KB — approaching the ceiling; plan "
                f"the split before it fails"
            )
    return out


# --- generated navigation ------------------------------------------------------------

def _documents(repo_root: Path) -> list[dict]:
    entries, _ = _load_entries(repo_root / "docs")
    return [e for e in entries if e.get("kind", "document") in DOCUMENT_KINDS]


def render_llms(repo_root: Path) -> str:
    """llms.txt. Links are relative to docs/, since that is where this file lives."""
    lines = [
        "# Casa — Home Assistant app",
        "",
        "Canonical current-state documentation for AI agents working on this repository.",
        "Code is the source of truth; these files are a map.",
        "",
    ]
    documents = _documents(repo_root)
    for title, prefix in SECTIONS:
        chosen = sorted(
            (e for e in documents if e["doc"].startswith(prefix)), key=lambda e: e["doc"]
        )
        if not chosen:
            continue
        lines += [f"## {title}", ""]
        for entry in chosen:
            lines.append(f"- [{entry['doc']}]({entry['doc']}): {entry['summary'].strip()}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_routing(repo_root: Path) -> str:
    """The README routing table, keyed on the task an agent is about to do.

    Phrased that way because an agent knows what it is about to change before it knows
    which subsystem owns it; the table has to meet it there.
    """
    rows = [GENERATED_NOTE, "", "| When you are changing… | Read |", "|---|---|"]
    for entry in sorted(_documents(repo_root), key=lambda e: e.get("when_changing", "")):
        rows.append(
            f"| {entry['when_changing'].strip()} | [`{entry['doc']}`]({entry['doc']}) |"
        )
    return "\n".join(rows) + "\n"


def _invariant_rows(repo_root: Path) -> list[tuple[str, str, str]]:
    """Every (id, statement, defining document), sorted by id."""
    docs_dir = repo_root / "docs"
    found: list[tuple[str, str, str]] = []
    for entry in _documents(repo_root):
        target = docs_dir / entry["doc"]
        if target.is_symlink() or not target.is_file():
            continue
        for line in target.read_text(errors="replace").splitlines():
            match = INV_DEFINITION.search(line)
            if match:
                found.append((match.group(1), line.split(":", 1)[1].strip(), entry["doc"]))
    return sorted(found)


# The index outgrew the 40 KB ceiling once the corpus passed ~200 invariants, so
# it shards by FAMILY letter — the same A-M / N-Z convention the manifest shards
# already use (#367). The split point is mechanical on purpose: an index that
# shards by meaning would need re-deciding every time a family is added.
_INV_SHARD_SPLIT = "N"


def _invariant_family(inv: str) -> str:
    """`INV-TG-006` -> `TG`. The family is what the shard split reads."""
    parts = inv.split("-")
    return parts[1] if len(parts) > 2 else ""


def _render_invariant_table(
    rows: list[tuple[str, str, str]], title: str, sibling: tuple[str, str],
) -> str:
    out = [
        f"# {title}",
        "",
        GENERATED_NOTE,
        "",
        CODE_WINS,
        "",
        "Every invariant is defined in exactly one file and referenced by id elsewhere.",
        "",
        f"The index is sharded by family letter: see also [`{sibling[0]}`]({sibling[1]}).",
        "",
        "| Id | Statement | Defined in |",
        "|---|---|---|",
    ]
    for inv, statement, home in rows:
        out.append(f"| `{inv}` | {statement} | [`{home}`](../{home}) |")
    return "\n".join(out) + "\n"


def render_invariants(repo_root: Path) -> str:
    """Families A-M: one row per INV-* id, its statement, its defining file."""
    rows = [r for r in _invariant_rows(repo_root)
            if _invariant_family(r[0]) < _INV_SHARD_SPLIT]
    return _render_invariant_table(
        rows, "Invariants (A-M)",
        ("doctrine/invariants-n-z.md", "invariants-n-z.md"))


def render_invariants_n_z(repo_root: Path) -> str:
    """Families N-Z. Same contract as :func:`render_invariants`."""
    rows = [r for r in _invariant_rows(repo_root)
            if _invariant_family(r[0]) >= _INV_SHARD_SPLIT]
    return _render_invariant_table(
        rows, "Invariants (N-Z)",
        ("doctrine/invariants.md", "invariants.md"))


def render_sourcemap(entry: dict) -> str:
    """The per-file Source & test map — generated, so no prose anchor drifts unverified."""
    # Links are relative to the DOCUMENT's own directory, not hardcoded one level up: a
    # future shard at architecture/memory/foo.md would otherwise emit broken links.
    depth = len(Path(entry["doc"]).parent.parts)
    up = "../" * depth if depth else ""
    lines = [GENERATED_NOTE, ""]
    for label, key in (("Source", "covers"), ("Tests", "tests")):
        anchors = entry.get(key) or []
        if anchors:
            lines.append(f"**{label}**")
            lines += [f"- `{anchor}`" for anchor in anchors]
            lines.append("")
    related = entry.get("related") or []
    if related:
        lines.append("**Related**")
        lines += [f"- [`{rel}`]({up}{rel})" for rel in related]
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _splice(text: str, begin: str, end: str, body: str, where: str) -> str:
    if text.count(begin) != 1 or text.count(end) != 1:
        raise SystemExit(f"{where}: needs exactly one {begin} / {end} pair")
    if text.index(begin) > text.index(end):
        raise SystemExit(f"{where}: {begin} / {end} markers are reversed")
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    return f"{head}{begin}\n{body}{end}{tail}"


def nav_targets(repo_root: Path) -> dict[str, str]:
    """Relative path -> expected full content, for every generated artifact."""
    docs_dir = repo_root / "docs"
    targets = {
        "llms.txt": render_llms(repo_root),
        "doctrine/invariants.md": render_invariants(repo_root),
        "doctrine/invariants-n-z.md": render_invariants_n_z(repo_root),
    }
    readme = docs_dir / "README.md"
    if readme.is_file():
        targets["README.md"] = _splice(
            readme.read_text(), ROUTING_BEGIN, ROUTING_END,
            render_routing(repo_root), "docs/README.md",
        )
    for entry in _documents(repo_root):
        target = docs_dir / entry["doc"]
        if target.is_symlink() or not target.is_file():
            continue
        text = target.read_text()
        if SOURCEMAP_BEGIN in text:
            targets[entry["doc"]] = _splice(
                text, SOURCEMAP_BEGIN, SOURCEMAP_END,
                render_sourcemap(entry), f"docs/{entry['doc']}",
            )
    return targets


def stale_nav(repo_root: Path) -> list[str]:
    """Which generated artifacts are out of date. Pure — writes nothing."""
    docs_dir = repo_root / "docs"
    stale = []
    for rel, expected in nav_targets(repo_root).items():
        target = docs_dir / rel
        if not target.exists() or target.read_text() != expected:
            stale.append(rel)
    return sorted(stale)


def write_nav(repo_root: Path) -> list[str]:
    """Write every generated artifact. Returns the ones whose content changed."""
    docs_dir = repo_root / "docs"
    changed = []
    for rel, expected in nav_targets(repo_root).items():
        target = docs_dir / rel
        if not target.exists() or target.read_text() != expected:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(expected)
            changed.append(rel)
    return sorted(changed)


# --- docs-impact ---------------------------------------------------------------------

def _claimants(entries: list[dict], changed: set[str]) -> set[str]:
    impacted = set()
    for entry in entries:
        if not isinstance(entry, dict) or not isinstance(entry.get("doc"), str):
            continue
        for anchor in entry.get("covers") or []:
            if isinstance(anchor, str) and parse_anchor(anchor)[0] in changed:
                impacted.add(entry["doc"])
    return impacted


def impacted_docs(
    repo_root: Path, changed: list[str], base_manifest: str | None = None
) -> set[str]:
    """Docs claiming any changed path, per the head manifest UNION the base manifest.

    The base manifest matters because the head one is editable in the same change: a PR
    could edit a source file and, in the same commit, delete the `covers` anchor, the
    manifest entry, or the document — leaving no claimant at head and a silently green
    check. Whatever claimed the surface *before* still has to answer for it.
    """
    entries, _ = _load_entries(repo_root / "docs")
    changed_set = set(changed)
    impacted = _claimants(entries, changed_set)
    if base_manifest:
        try:
            base_entries = yaml.safe_load(base_manifest) or []
        except yaml.YAMLError:
            base_entries = []
        if isinstance(base_entries, list):
            impacted |= _claimants(base_entries, changed_set)
    return impacted


# --- cli -----------------------------------------------------------------------------

def main() -> int:
    args = sys.argv[1:]
    positional = [a for a in args if not a.startswith("-")]
    root = Path(positional[0] if positional else ".").resolve()

    if "--impact" in args:
        raw = sys.stdin.read()
        if raw == "":
            # ZERO bytes is a bare invocation (stdin /dev/null), which used to
            # report an empty impact set as a clean one — measured: a headless
            # session recorded "no impacted docs" from exactly this call. An
            # EMPTY DIFF is different and stays fine: docs_impact.sh pipes at
            # least one newline even when nothing changed.
            print("✗ --impact read zero bytes on stdin; pipe the changed paths:")
            print("      git diff --name-only <base>...HEAD | "
                  "python -m scripts.verify_docs . --impact")
            return 1
        changed = [line.strip() for line in raw.splitlines() if line.strip()]
        base_manifest = None
        if "--base-manifest" in args:
            # Fail CLOSED. Silently dropping a requested base manifest reinstates the exact
            # bypass impacted_docs() exists to close: delete the claim at head, lose the base,
            # and the check reports no claimant.
            base_path = Path(args[args.index("--base-manifest") + 1])
            if not base_path.exists():
                print(f"✗ --base-manifest {base_path} does not exist")
                return 1
            base_manifest = base_path.read_text()
            try:
                parsed = yaml.safe_load(base_manifest)
            except yaml.YAMLError as exc:
                print(f"✗ --base-manifest {base_path} is not valid YAML: {exc}")
                return 1
            if parsed is not None and not isinstance(parsed, list):
                print(f"✗ --base-manifest {base_path} is not a list of entries")
                return 1
        for doc in sorted(impacted_docs(root, changed, base_manifest)):
            print(doc)
        return 0

    if "--report" in args and (root / "docs" / "manifest.yaml").exists():
        docs_dir = root / "docs"
        entries, _ = _load_entries(docs_dir)
        sizes = [
            (entry["doc"], (docs_dir / entry["doc"]).stat().st_size)
            for entry in entries
            if (docs_dir / entry["doc"]).is_file()
        ]
        for doc, size in sorted(sizes, key=lambda pair: -pair[1]):
            print(f"{size / 1000:7.1f} KB  {doc}")
        near = sum(1 for _, size in sizes if size >= WARN_BYTES)
        total = sum(size for _, size in sizes)
        print(f"\n{len(sizes)} files, {total / 1000:.1f} KB total, {near} within 20% of the ceiling")

    if "--write-nav" in args:
        for rel in write_nav(root):
            print(f"✓ regenerated docs/{rel}")
    # Nav staleness is checked UNCONDITIONALLY (v0.130.0 follow-up): the gate
    # always ran --check-nav, but the documented keep-me-green invocation is
    # the bare `python -m scripts.verify_docs .` — which used to pass on a
    # stale routing table or source map and let the mismatch surface only at
    # push time. A local green must mean gate green. `--check-nav` remains
    # accepted for existing callers; after --write-nav the check is trivially
    # fresh.
    stale = stale_nav(root)
    if stale:
        print("✗ generated navigation is stale: " + ", ".join(stale))
        print("  run: python -m scripts.verify_docs . --write-nav")
        return 1

    for warning in warnings(root):
        print(f"! {warning}")

    problems = verify(root)
    # The coverage ledger is part of the corpus contract: a surface the code grows that
    # no document claims is the same defect as a document claiming code that is gone.
    ledger_script = Path(__file__).resolve().parent / "coverage_ledger.py"
    if ledger_script.exists() and (root / "docs" / "coverage.yaml").exists():
        result = subprocess.run(
            [sys.executable, str(ledger_script), "check", str(root)],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            problems.extend(
                line.lstrip("✗ ").rstrip()
                for line in result.stdout.splitlines()
                if line.startswith("✗")
            )
    for problem in problems:
        print(f"✗ {problem}")
    if problems:
        print(f"\n{len(problems)} problem(s).")
        return 1
    print("✓ docs corpus verified")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
